name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setting up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.dev.txt
    - name: Running Tests
      run: |
        python -m coverage run --source=. -m unittest --verbose --locals tests
    - name: Upload Coverage Data
      uses: actions/upload-artifact@v4
      with:
        name: coverage-data
        path: .coverage
        include-hidden-files: true # Without this, it won't read files starting with '.'
        if-no-files-found: error
